apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-notebook
  labels:
    app: tensorflow-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow-notebook
  template:
    metadata:
      labels:
        app: tensorflow-notebook
    spec:
      containers:
      - name: tensorflow-notebook
        image: eubraatmosphere/eubraatmosphere_autobuild:tensorflow-notebook
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: tensorflow-notebook
spec:
  type: NodePort
  selector:
    app: tensorflow-notebook
  ports:
  - protocol: TCP
    nodePort: 30050
    port: 8888
    targetPort: 8888
