kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sshserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sshserver
    spec:
      volumes:
        - name: sshserver
          persistentVolumeClaim:
           claimName: task-pv-claim
      containers:
        - name: sshd
          image: eubraatmosphere/eubraatmosphere_autobuild:ub16_sshd
          env:
            - name: SSHKEY
              valueFrom:
                secretKeyRef:
                  name: sshfs-secret
                  key: sshpubkey
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: "/share/vol001"
              name: sshserver
---
kind: Service
apiVersion: v1
metadata:
  name: sshserver
spec:
#  type: NodePort
  selector:
    app: sshserver
  ports:
  - protocol: TCP
#    nodePort: 30010
    port: 22
    targetPort: 22

