

kind: Service
apiVersion: v1
metadata:
  name: wncluster
spec:
  selector:
    app: clusterworker
  ports:
  - protocol: TCP
    port: 9376
    name: nginx
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clusterworker
spec:
  serviceName: "wncluster"
  # Adjust the number of replicas
  replicas: 4
  selector:
    matchLabels:
      app: clusterworker
  template:
    metadata:
      labels: 
        app: clusterworker
    spec:
      containers:
       - name: opencvfilter
         image: eubraatmosphere/eubraatmosphere_autobuild:ub16_ssfstf11-client
         resources:
           limits:
             cpu: "1"
           requests:
             cpu: "0.5"
         args: [ 'ipengine --file=/mnt/.ipython/profile_default/security/ipcontroller-engine.json' ]
         securityContext:
           privileged: true
         env:
           - name: SSHPRIVKEY
             valueFrom:
               secretKeyRef:
                 name: sshfs-secret
                 key: sshprivkey
           - name: SSHPUBKEY
             valueFrom:
               secretKeyRef:
                name: sshfs-secret
                key: sshpubkey
           - name: SERVER
             valueFrom:
               configMapKeyRef:
                 name: sshfs-configmap
                 key: server
           - name: MOUNTPOINT
             valueFrom:
               configMapKeyRef:
                 name: sshfs-configmap
                 key: mountpoint
#           - name: SKIPMOUNT
#             value: "true"
