kind: Service
apiVersion: v1
metadata:
  name: tfcluster
spec:
  selector:
    app: clusterworker
  ports:
  - protocol: TCP
    port: 9376
    name: nginx
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clusterworker
spec:
  serviceName: "tfcluster"
  replicas: 1
  selector:
    matchLabels:
      app: clusterworker
  template:
    metadata:
      labels: 
        app: clusterworker
    spec:
      containers:
       - name: opencvfilter
         image: eubraatmosphere/eubraatmosphere_autobuild:ub16gpu_ssfstf10-client
         resources:
           limits:
             nvidia.com/gpu: 1 #Number of GPUs
             cpu: "1"
           requests:
             cpu: "0.5"
             # args: [ 'python3 /usr/local/bin/mnist_worker.py --job_name=worker --task_index=$(hostname| sed -e "s/clusterworker-//") --worker_hosts=clusterworker-0.tfcluster.default.svc.cluster.local:8000,clusterworker-1.tfcluster.default.svc.cluster.local:8000 --ps_hosts=psserver-0.psserver.default.svc.cluster.local:8000 & ipengine --file=/mnt/.ipython/profile_default/security/ipcontroller-engine.json' ]
         args: [ 'CUDA_VISIBLE_DEVICES=$(hostname| sed -e "s/clusterworker-//") python3 /usr/local/bin/mnist_worker.py --job_name=worker --task_index=$(hostname| sed -e "s/clusterworker-//") --worker_hosts=$WNLIST --ps_hosts=$PSLIST & ipengine --file=/mnt/.ipython/profile_default/security/ipcontroller-engine.json' ]
         securityContext:
           privileged: true
         env:
           - name: PSLIST
             valueFrom:
               configMapKeyRef:
                 name: distrib-tf
                 key: ps-list
           - name: WNLIST
             valueFrom:
               configMapKeyRef:
                 name: distrib-tf
                 key: wn-list
           - name: SSHPRIVKEY
             valueFrom:
               secretKeyRef:
                 name: sshfs-secret
                 key: sshprivkey
           - name: SSHPUBKEY
             valueFrom:
               secretKeyRef:
                name: sshfs-secret
                key: sshpubkey
           - name: SERVER
             valueFrom:
               configMapKeyRef:
                 name: sshfs-configmap
                 key: server
           - name: MOUNTPOINT
             valueFrom:
               configMapKeyRef:
                 name: sshfs-configmap
                 key: mountpoint
#           - name: SKIPMOUNT
#             value: "true"

